stages:
  - build
  - deploy

build front:
  stage: build
  image: node:lts-alpine3.16

#puedo configurar que se ejecute el stage unicamente en cuando hay cambios en main
#en este caso la quiero desplegar en mi rama por eso no pongo esa condicion  

  script:
    - npm install
#CI=false se coloca para evitar que no se ejecute el Stage por un warning de npm 
    - CI=false npm run build
 #   - npm run build
  artifacts:
    paths:
      - build
    expire_in: 30 days

despliegue en s3:
  stage: deploy

  when: manual 
#imagen dockerizada del CLI de amazon
  image: 
    name: amazon/aws-cli
#se utiliza para que el contenedor funcione como un ejecutable 
    entrypoint: [""]
  script:
    - aws --version
#elimina los objetos en s3
    - aws s3 rm s3://$S3_BUCKET --recursive
#copia los archivos locales u objetos y los pega en una ubicacion s3
    - aws s3 cp build s3://$S3_BUCKET --recursive